name: Pipeline Completo

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint NPM
        id: lint
        run: npm run lint

  unit:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        id: deps
        run: npm ci

      - name: Run unit tests
        id: test
        run: |
          npm test -- --coverage --coverageReporters=json
          echo "coverage=$(jq .total.lines.pct coverage/coverage-summary.json)" >> "$GITHUB_OUTPUT"
    outputs:
      coverage: ${{ steps.test.outputs.coverage }}

  docker:
    permissions:
      contents: read
      packages: write
    needs: unit
    if: ${{ needs.unit.outputs.coverage >= 80 }}
    runs-on: ubuntu-latest
    env:
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        id: docker_login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: build_push
        run: |
          repo_lc=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          image="ghcr.io/${repo_lc}/password-meter:${GITHUB_SHA}"
          docker build \
            --build-arg GH_PACKAGES_TOKEN \
            -t "$image" \
            .
          docker push "$image"
          echo "image=$image" >> "$GITHUB_OUTPUT"
    outputs:
      image: ${{ steps.build_push.outputs.image }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Print image
        run: echo "Deploying ${{ needs.docker.outputs.image }}"
      
      - name: Deploy to production
        run: |
          echo "🚀 Deploying password strength meter to production"
          echo "📦 Image: ${{ needs.docker.outputs.image }}"
          echo "✅ Deployment completed successfully!"